name: Test
on:
  workflow_dispatch:
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initial check
        run: lsb release -a

      - name: run multiple commands
        run: |
          pwd,
          ls-a,
          java -version,
          mvn --version,
          gradle --version,
          ant --version,
          echo Android sdk,
          echo $ANDROID_SDK_ROOT,
          echo $SELENIUM_JAR_PATH,
          echo $RUNNER_WORKSPACE,
          whoami
          df
