name: test-2
on:
  workflow_dispatch:
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: read the readme file
      run: |
        ls -R
        head README.md
