name: test-2
on:
  workflow_dispatch:
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: read the readme file
      run: |
        ls -a
        head README.md > wf_file
        ls -a
        mkdir result
        head wf_file > result/wf_file2
        ls -R
